SET HTTP_PROXY=http://CptLinuxWeb:LinuxWeb@HAI1-TT-SQUID.TESSI-TECHNO.FR:3128
SET HTTPS_PROXY=http://CptLinuxWeb:LinuxWeb@HAI1-TT-SQUID.TESSI-TECHNO.FR:3128

composer update

SET HTTP_PROXY=""
SET HTTPS_PROXY=""

